language: go
sudo: false
go:
  - "1.9.x"
  - "1.10.x"
go_import_path: github.com/tech-sketch/fiware-ambassador-auth
script:
  - go vet ./...
  - diff <(golint ./... | grep -v vendor/) <(printf "")
  - go test ./...
